spring:
  data:
    mongodb:
      host: auth-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: manage_center
      port: 27017

server:
  context-path: /uaa
  port: 5000